//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  news: News;
  newsConnection: NewsConnection;
  gallery: Gallery;
  galleryConnection: GalleryConnection;
  stats: Stats;
  statsConnection: StatsConnection;
  programs: Programs;
  programsConnection: ProgramsConnection;
  tiers: Tiers;
  tiersConnection: TiersConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
};


export type QueryGalleryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
};


export type QueryStatsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStatsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StatsFilter>;
};


export type QueryProgramsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProgramsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgramsFilter>;
};


export type QueryTiersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTiersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TiersFilter>;
};

export type DocumentFilter = {
  news?: InputMaybe<NewsFilter>;
  gallery?: InputMaybe<GalleryFilter>;
  stats?: InputMaybe<StatsFilter>;
  programs?: InputMaybe<ProgramsFilter>;
  tiers?: InputMaybe<TiersFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = News | Gallery | Stats | Programs | Tiers | Folder;

export type News = Node & Document & {
  __typename?: 'News';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  month: Scalars['String']['output'];
  day: Scalars['String']['output'];
  year: Scalars['String']['output'];
  category: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NewsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  month?: InputMaybe<StringFilter>;
  day?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type NewsConnectionEdges = {
  __typename?: 'NewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<News>;
};

export type NewsConnection = Connection & {
  __typename?: 'NewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NewsConnectionEdges>>>;
};

export type Gallery = Node & Document & {
  __typename?: 'Gallery';
  src: Scalars['String']['output'];
  alt: Scalars['String']['output'];
  span?: Maybe<Scalars['String']['output']>;
  order: Scalars['Float']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type GalleryFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  span?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type GalleryConnectionEdges = {
  __typename?: 'GalleryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Gallery>;
};

export type GalleryConnection = Connection & {
  __typename?: 'GalleryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleryConnectionEdges>>>;
};

export type Stats = Node & Document & {
  __typename?: 'Stats';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
  order: Scalars['Float']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type StatsConnectionEdges = {
  __typename?: 'StatsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Stats>;
};

export type StatsConnection = Connection & {
  __typename?: 'StatsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StatsConnectionEdges>>>;
};

export type Programs = Node & Document & {
  __typename?: 'Programs';
  title: Scalars['String']['output'];
  level: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  ages: Scalars['String']['output'];
  description: Scalars['String']['output'];
  color: Scalars['String']['output'];
  image: Scalars['String']['output'];
  imageAlt: Scalars['String']['output'];
  order: Scalars['Float']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProgramsFilter = {
  title?: InputMaybe<StringFilter>;
  level?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  ages?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ProgramsConnectionEdges = {
  __typename?: 'ProgramsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Programs>;
};

export type ProgramsConnection = Connection & {
  __typename?: 'ProgramsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProgramsConnectionEdges>>>;
};

export type Tiers = Node & Document & {
  __typename?: 'Tiers';
  amount: Scalars['Float']['output'];
  label: Scalars['String']['output'];
  period: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  highlighted?: Maybe<Scalars['Boolean']['output']>;
  order: Scalars['Float']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TiersFilter = {
  amount?: InputMaybe<NumberFilter>;
  label?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  highlighted?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TiersConnectionEdges = {
  __typename?: 'TiersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tiers>;
};

export type TiersConnection = Connection & {
  __typename?: 'TiersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TiersConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateNews: News;
  createNews: News;
  updateGallery: Gallery;
  createGallery: Gallery;
  updateStats: Stats;
  createStats: Stats;
  updatePrograms: Programs;
  createPrograms: Programs;
  updateTiers: Tiers;
  createTiers: Tiers;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationCreateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationUpdateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationCreateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationUpdateStatsArgs = {
  relativePath: Scalars['String']['input'];
  params: StatsMutation;
};


export type MutationCreateStatsArgs = {
  relativePath: Scalars['String']['input'];
  params: StatsMutation;
};


export type MutationUpdateProgramsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgramsMutation;
};


export type MutationCreateProgramsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgramsMutation;
};


export type MutationUpdateTiersArgs = {
  relativePath: Scalars['String']['input'];
  params: TiersMutation;
};


export type MutationCreateTiersArgs = {
  relativePath: Scalars['String']['input'];
  params: TiersMutation;
};

export type DocumentUpdateMutation = {
  news?: InputMaybe<NewsMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  stats?: InputMaybe<StatsMutation>;
  programs?: InputMaybe<ProgramsMutation>;
  tiers?: InputMaybe<TiersMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  news?: InputMaybe<NewsMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  stats?: InputMaybe<StatsMutation>;
  programs?: InputMaybe<ProgramsMutation>;
  tiers?: InputMaybe<TiersMutation>;
};

export type NewsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  month?: InputMaybe<Scalars['String']['input']>;
  day?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  span?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type StatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type ProgramsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  level?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  ages?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type TiersMutation = {
  amount?: InputMaybe<Scalars['Float']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  highlighted?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type NewsPartsFragment = { __typename: 'News', title: string, date: string, month: string, day: string, year: string, category: string, description?: string | null, image?: string | null, imageAlt?: string | null };

export type GalleryPartsFragment = { __typename: 'Gallery', src: string, alt: string, span?: string | null, order: number };

export type StatsPartsFragment = { __typename: 'Stats', value: string, label: string, order: number };

export type ProgramsPartsFragment = { __typename: 'Programs', title: string, level: string, icon: string, ages: string, description: string, color: string, image: string, imageAlt: string, order: number };

export type TiersPartsFragment = { __typename: 'Tiers', amount: number, label: string, period: string, description: string, icon: string, highlighted?: boolean | null, order: number };

export type NewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NewsQuery = { __typename?: 'Query', news: { __typename: 'News', id: string, title: string, date: string, month: string, day: string, year: string, category: string, description?: string | null, image?: string | null, imageAlt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
}>;


export type NewsConnectionQuery = { __typename?: 'Query', newsConnection: { __typename?: 'NewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NewsConnectionEdges', cursor: string, node?: { __typename: 'News', id: string, title: string, date: string, month: string, day: string, year: string, category: string, description?: string | null, image?: string | null, imageAlt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GalleryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GalleryQuery = { __typename?: 'Query', gallery: { __typename: 'Gallery', id: string, src: string, alt: string, span?: string | null, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GalleryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
}>;


export type GalleryConnectionQuery = { __typename?: 'Query', galleryConnection: { __typename?: 'GalleryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GalleryConnectionEdges', cursor: string, node?: { __typename: 'Gallery', id: string, src: string, alt: string, span?: string | null, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type StatsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StatsQuery = { __typename?: 'Query', stats: { __typename: 'Stats', id: string, value: string, label: string, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type StatsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StatsFilter>;
}>;


export type StatsConnectionQuery = { __typename?: 'Query', statsConnection: { __typename?: 'StatsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StatsConnectionEdges', cursor: string, node?: { __typename: 'Stats', id: string, value: string, label: string, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProgramsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProgramsQuery = { __typename?: 'Query', programs: { __typename: 'Programs', id: string, title: string, level: string, icon: string, ages: string, description: string, color: string, image: string, imageAlt: string, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProgramsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgramsFilter>;
}>;


export type ProgramsConnectionQuery = { __typename?: 'Query', programsConnection: { __typename?: 'ProgramsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProgramsConnectionEdges', cursor: string, node?: { __typename: 'Programs', id: string, title: string, level: string, icon: string, ages: string, description: string, color: string, image: string, imageAlt: string, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TiersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TiersQuery = { __typename?: 'Query', tiers: { __typename: 'Tiers', id: string, amount: number, label: string, period: string, description: string, icon: string, highlighted?: boolean | null, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TiersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TiersFilter>;
}>;


export type TiersConnectionQuery = { __typename?: 'Query', tiersConnection: { __typename?: 'TiersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TiersConnectionEdges', cursor: string, node?: { __typename: 'Tiers', id: string, amount: number, label: string, period: string, description: string, icon: string, highlighted?: boolean | null, order: number, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const NewsPartsFragmentDoc = gql`
    fragment NewsParts on News {
  __typename
  title
  date
  month
  day
  year
  category
  description
  image
  imageAlt
}
    `;
export const GalleryPartsFragmentDoc = gql`
    fragment GalleryParts on Gallery {
  __typename
  src
  alt
  span
  order
}
    `;
export const StatsPartsFragmentDoc = gql`
    fragment StatsParts on Stats {
  __typename
  value
  label
  order
}
    `;
export const ProgramsPartsFragmentDoc = gql`
    fragment ProgramsParts on Programs {
  __typename
  title
  level
  icon
  ages
  description
  color
  image
  imageAlt
  order
}
    `;
export const TiersPartsFragmentDoc = gql`
    fragment TiersParts on Tiers {
  __typename
  amount
  label
  period
  description
  icon
  highlighted
  order
}
    `;
export const NewsDocument = gql`
    query news($relativePath: String!) {
  news(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NewsParts
  }
}
    ${NewsPartsFragmentDoc}`;
export const NewsConnectionDocument = gql`
    query newsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NewsFilter) {
  newsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NewsParts
      }
    }
  }
}
    ${NewsPartsFragmentDoc}`;
export const GalleryDocument = gql`
    query gallery($relativePath: String!) {
  gallery(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleryParts
  }
}
    ${GalleryPartsFragmentDoc}`;
export const GalleryConnectionDocument = gql`
    query galleryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleryFilter) {
  galleryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleryParts
      }
    }
  }
}
    ${GalleryPartsFragmentDoc}`;
export const StatsDocument = gql`
    query stats($relativePath: String!) {
  stats(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StatsParts
  }
}
    ${StatsPartsFragmentDoc}`;
export const StatsConnectionDocument = gql`
    query statsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StatsFilter) {
  statsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StatsParts
      }
    }
  }
}
    ${StatsPartsFragmentDoc}`;
export const ProgramsDocument = gql`
    query programs($relativePath: String!) {
  programs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProgramsParts
  }
}
    ${ProgramsPartsFragmentDoc}`;
export const ProgramsConnectionDocument = gql`
    query programsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProgramsFilter) {
  programsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProgramsParts
      }
    }
  }
}
    ${ProgramsPartsFragmentDoc}`;
export const TiersDocument = gql`
    query tiers($relativePath: String!) {
  tiers(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TiersParts
  }
}
    ${TiersPartsFragmentDoc}`;
export const TiersConnectionDocument = gql`
    query tiersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TiersFilter) {
  tiersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TiersParts
      }
    }
  }
}
    ${TiersPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      news(variables: NewsQueryVariables, options?: C): Promise<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}> {
        return requester<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}, NewsQueryVariables>(NewsDocument, variables, options);
      },
    newsConnection(variables?: NewsConnectionQueryVariables, options?: C): Promise<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}> {
        return requester<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}, NewsConnectionQueryVariables>(NewsConnectionDocument, variables, options);
      },
    gallery(variables: GalleryQueryVariables, options?: C): Promise<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}> {
        return requester<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}, GalleryQueryVariables>(GalleryDocument, variables, options);
      },
    galleryConnection(variables?: GalleryConnectionQueryVariables, options?: C): Promise<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}> {
        return requester<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}, GalleryConnectionQueryVariables>(GalleryConnectionDocument, variables, options);
      },
    stats(variables: StatsQueryVariables, options?: C): Promise<{data: StatsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsQueryVariables, query: string}> {
        return requester<{data: StatsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsQueryVariables, query: string}, StatsQueryVariables>(StatsDocument, variables, options);
      },
    statsConnection(variables?: StatsConnectionQueryVariables, options?: C): Promise<{data: StatsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsConnectionQueryVariables, query: string}> {
        return requester<{data: StatsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsConnectionQueryVariables, query: string}, StatsConnectionQueryVariables>(StatsConnectionDocument, variables, options);
      },
    programs(variables: ProgramsQueryVariables, options?: C): Promise<{data: ProgramsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsQueryVariables, query: string}> {
        return requester<{data: ProgramsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsQueryVariables, query: string}, ProgramsQueryVariables>(ProgramsDocument, variables, options);
      },
    programsConnection(variables?: ProgramsConnectionQueryVariables, options?: C): Promise<{data: ProgramsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsConnectionQueryVariables, query: string}> {
        return requester<{data: ProgramsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsConnectionQueryVariables, query: string}, ProgramsConnectionQueryVariables>(ProgramsConnectionDocument, variables, options);
      },
    tiers(variables: TiersQueryVariables, options?: C): Promise<{data: TiersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiersQueryVariables, query: string}> {
        return requester<{data: TiersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiersQueryVariables, query: string}, TiersQueryVariables>(TiersDocument, variables, options);
      },
    tiersConnection(variables?: TiersConnectionQueryVariables, options?: C): Promise<{data: TiersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiersConnectionQueryVariables, query: string}> {
        return requester<{data: TiersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiersConnectionQueryVariables, query: string}, TiersConnectionQueryVariables>(TiersConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/1.5/content/9bff4b70-8364-4205-b688-7c79939891bf/github/tina",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  